name: integration-tests
on:
  push:
    branches: [ main ]
  pull_request:

env:
  GRADLE_OPTS: "-Xmx6g -Dorg.gradle.daemon=false"
  total-runners: 6

jobs:
  integration-test:
    runs-on: [ self-hosted, Linux, X64 ]
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: export runner UID
        run: echo "runner_uid=$UID" >> $GITHUB_ENV
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Restore classes
        uses: actions/cache@v3
        with:
          path: "**/*.class"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
      - name: test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: integrationTest
      - name: Correct Ownership in GITHUB_WORKSPACE directory
        uses: peter-murray/reset-workspace-ownership-action@v1
        with:
          user_id: ${{ env.runner_uid }}
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: always() # always run even if the previous step fails
        with:
          name: junit-integration-test-results
          path: '**/build/test-results/integrationTest/TEST-*.xml'
          retention-days: 1