# SPDX-License-Identifier: Apache-2.0
# Hyperledger Repolinter Action
name: Repolinter

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: export runner UID
        run: echo "runner_uid=$UID" >> $GITHUB_ENV
      - name: list perms
        run: ls -la
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: list perms
        run: ls -la
      - name: 'Run Repolinter'
        uses: newrelic/repolinter-action@v1
        with:
          config_url: https://raw.githubusercontent.com/hyperledger-labs/hyperledger-community-management-tools/main/repo_structure/repolint.json
      - name: list perms
        run: ls -la
      - name: Correct Ownership in GITHUB_WORKSPACE directory
        uses: peter-murray/reset-workspace-ownership-action@v1
        with:
          user_id: ${{ env.runner_uid }}
