name: testbed
on:
  push:

jobs:
  compile:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 30
    steps:
      - name: export runner UID
        run: echo "runner_uid=$UID" >> $GITHUB_ENV
      - name: use runner UID
        run: echo "${{ env.runner_uid }}"